platform :ios, '9.0'
target ‘YouDian_AR’  do
pod 'AFNetworking', '~>3.1.0'
pod 'Masonry', '~> 1.1.0'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'Toast', '~> 4.0.0'
pod 'FMDB', '~> 2.7.2'
pod 'YYModel', '~> 1.0.4'
pod 'SDWebImage', '~> 4.3.3'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'MBProgressHUD-Extension', '~> 2.0.0'
pod 'IQKeyboardManager', '~> 6.0.3'
pod 'SVProgressHUD', '~> 2.2.5'
pod 'PNChart', '~> 0.8.9'
pod 'UMCCommon'
pod 'UMCAnalytics'
pod 'UMCSecurityPlugins'
pod 'UMCShare/UI'
pod 'UMCShare/Social/WeChat'
pod 'UMCShare/Social/QQ'
pod 'AMapLocation-NO-IDFA'
pod 'BGSegementController'

end
